run:
  issues-exit-code: 1
  timeout: 5m

linters-settings:
  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus
      - log
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 3
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/xelaj/tl
  revive:
    min-confidence: 0
    enable-all-rules: true
    rules:
      - { name: function-length, arguments: [10, 0] }
      - { name: argument-limit, arguments: [4] }
      - { name: file-header, disabled: true }
      - { name: banned-characters, disabled: true }
      - { name: cognitive-complexity, arguments: [7] }
      - { name: function-result-limit, arguments: [2] }
      - { name: cyclomatic, disabled: true }
      - { name: line-length-limit, disabled: true }
      - { name: max-public-structs, arguments: [15] }

  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: [argument, case, condition, return]
  govet:
    check-shadowing: true
    enable-all: true
  lll:
    line-length: 100
  misspell:
    locale: US
  goheader:
    values:
      const:
        OWNER_COMPANY: Xelaj Software
        LICENSE_URL: https://github.com/xelaj/tl/blob/master/LICENSE.md
    template-path: docs/.license_header.txt
  ireturn:
    reject:
      - anon

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    # - bodyclose # 1.18 incompatible
    - containedctx
    # - contextcheck # 1.18 incompatible
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustivestruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    # - gocritic # 1.18 incompatible
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    # - gosimple # 1.18 incompatible
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    # - interfacer # deprecated
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    # - nilerr # 1.18 incompatible
    - nilnil
    - nlreturn
    # - noctx # 1.18 incompatible
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    # - rowserrcheck # 1.18 incompatible
    # - sqlclosecheck # 1.18 incompatible
    # - staticcheck # 1.18 incompatible
    # - structcheck # 1.18 incompatible
    # - stylecheck # 1.18 incompatible
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    # - tparallel # 1.18 incompatible
    - typecheck
    - unconvert
    # - unparam # 1.18 incompatible
    # - unused # 1.18 incompatible
    - varcheck
    # - varnamelen
    # - wastedassign # 1.18 incompatible
    - whitespace
    - wrapcheck
    # - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gomnd
        - errcheck

service:
  project-path: github.com/xelaj/logger
  golangci-lint-version: 1.45.x
