// @type some cool enums!
// @enum this is really cool enum!
someEnum#5508ec75 = CoolEnumerate;

// @type some cool struct
// @constructor make it struct!
// @param paramA this is the A paramateter
// @param paramB and this is the B one.
constructor#12345678 paramA:string paramB:bool = CoolStruct;
constructorNoFields#12345678 = CoolStruct;
constructorWithoutComments#12345678 flags:# a:flags.1?true = CoolStruct;
