default: true

MD013:
  line_length: 80
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false

MD026: false
MD033:
  # Allowed elements
  allowed_elements: ["p", "sub", "sup", "img", "a"]
MD043: false
